name: my_new_cv
description: "A professional CV generator app"
version: 1.0.4+4
publish_to: 'none'

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.9.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  pdf: ^3.11.1
  printing: ^5.11.1
  dart_openai: ^6.1.1 
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  google_sign_in: ^6.2.1
  firebase_database: ^12.1.2
  battery_plus: ^7.0.0
  connectivity_plus: ^7.0.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  intl: ^0.20.2
  google_fonts: ^8.0.0
  http: ^1.1.0
  url_launcher: ^6.3.0
  firebase_remote_config: ^6.1.4
  package_info_plus: ^9.0.0
  share_plus: ^12.0.1
  device_info_plus: ^12.3.0
  intl_phone_field: ^3.2.0
  shared_preferences: ^2.5.4
  open_filex: ^4.5.0
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0 # እዚህ ጋር ተጨምሯል

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app_icon.png"

# ስፕላሽ ስክሪን ኮንፊገሬሽን
flutter_native_splash:
  color: "#3F51B5"
  image: "assets/app_icon.png"
  android_12:
    image: "assets/app_icon.png"
    color: "#3F51B5"
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/canva_black_white.png
    - assets/google_logo.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: Arimo
      fonts:
        - asset: assets/fonts/Arimo-Regular.ttf
        - asset: assets/fonts/Arimo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Arimo-Italic.ttf
          style: italic
        - asset: assets/fonts/Arimo-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Arimo-VariableFont_wght.ttf
        - asset: assets/fonts/Arimo-Italic-VariableFont_wght.ttf
          style: italic

    - family: Times
      fonts:
        - asset: assets/fonts/times_regular.ttf
        - asset: assets/fonts/times_bold.ttf
          weight: 700

    - family: Abyssinica
      fonts:
        - asset: assets/fonts/AbyssinicaSIL-Regular.ttf
        - asset: assets/fonts/abyssinica.ttf

    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif-Regular.ttf
        - asset: assets/fonts/NotoSerif-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSerif-Italic.ttf
          style: italic
        - asset: assets/fonts/NotoSerif-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/NotoSerifEthiopic-VariableFont_wdth,wght.ttf